### ISSUE TITLE
Output probability for each class  

### ISSUE THREAD

**Issue by alvaannett** [lcmmichielsen/hierarchicalprogressivelearning#9]
Hello, 

Is there a way to output the probability for each cell to belong to each class?

Best, 
Alva

**Comment by lcmmichielsen** [comment]
Hi Alva,

This is not possible yet, but I can add this option in the coming weeks.

Cheers,
Lieke

**Comment by alvaannett** [comment]
Thank you, that would be great! :) 

Best, 
Alva

**Comment by lcmmichielsen** [comment]
Sorry for the late reply! I just implemented the possibility of returning the probabilities. You can download this version from the pip repository. This only works when using the kNN classifier though (the linear and one-class SVM in sklearn only returns a score instead of a probability). You can get the probabilities by running the following:

`y_pred, y_prob = predict.predict_labels(testdata,tree)`

Hope this helps!

**Comment by alvaannett** [comment]
Thank you so much! :)
